### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by matheusrocha89** [FormidableLabs/webpack-stats-plugin#16]
When I try to run the build process with webpack I am having this error:
```
Unhandled rejection TypeError: Cannot read property '0' of undefined
    at Object.transform (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/webpack/prod.config.js:83:42)
    at Compiler.<anonymous> (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/webpack-stats-plugin/lib/stats-writer-plugin.js:74:32)
    at Compiler.next (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/tapable/lib/Tapable.js:69:14)
    at /Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/html-webpack-plugin/index.js:203:9
    at PassThroughHandlerContext.finallyHandler (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/bluebird/js/release/finally.js:55:23)
    at PassThroughHandlerContext.tryCatcher (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/matheus/Development/jusbrasil_projects/deadpool-dashboard/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

```

**Comment by ryan-roemer** [comment]
@matheusrocha89 -- Can you

1. Tell us what version you're using?
2. If not `v0.1.3`, downgrade and try that?
3. Point us to your webpack config + full project if it's open source?

Thanks!

**Comment by matheusrocha89** [comment]
The version I am using is `0.1.4`
The code is not open :/
The branch that the error start adds some new packages to the project like, redux, redux-thunk, whatwg-fetch, lodash.

Right now I am using git bisect to discover which commit starts the problem. But just to say on my webpack dev config I am using this on plugins array to use the whatwg-fetch:
```javascript
new webpack.ProvidePlugin({
  'fetch': 'imports?this=>global!exports?global.fetch!whatwg-fetch'
}),
```

**Comment by matheusrocha89** [comment]
Found the problem and solved. God bless `git bisect` :) It was a problem on my webpack configuration, my bad, sorry. I'm ashamed.
![image](https://cloud.githubusercontent.com/assets/3718366/19913139/b1b6ac52-a07e-11e6-9e57-7c1fb3a68a81.png)

**Comment by ryan-roemer** [comment]
haha, no worries. And ❤️ `git bisect`...

**Comment by morajabi** [comment]
I have this error too.

**Comment by ryan-roemer** [comment]
Like the previous poster, can @morajabi -- Can you

1. Tell us what version you're using?
2. If not `v0.1.3`, downgrade and try that?
3. Point us to your webpack config + full project if it's open source?

Thanks!

( _very likely you aren't actually producing **any** bundles and have an error in your configuration_ )

**Comment by matheusrocha89** [comment]
@morajabi Check your `webpack` configuration, my problem was that.
